version: '2'

services:
    topeightbackend:
        volumes:
            - .:/top_eight
            - ../certs:/certs

            # necessary to prevent OS X node_modules being loaded in:
            - /top_eight/backend/node_modules

        build:
            context: ./backend
            dockerfile: ./Dockerfile

        ports:
            - "3002:8000"

        links:
            - cache
    cache:
        image: redis:3.0
        ports:
            - '4379:6379'
